### ISSUE TITLE
'Property Tranfer Tax' PTT tax type totals not collected

### ISSUE THREAD

**Issue by rahensonzam** [nextgensparx/zra-helper#108]
v1.4.0-beta.1-chrome

'Get pending liabilities' action not collecting totals from 'Property Transfer Tax' tax type with code CLIENT-PTT

**Comment by siphomateke** [comment]
What do you mean "with code CLIENT-PTT"? Is that the format that property transfer tax account names are in? For example, "HENSON-PTT"? As far as I was aware, the format for PTT accounts was "HENSON-PROPERTY TRANSFER TAX".

Does the "Get PTT totals" task show up when getting pending liabilities?

**Comment by rahensonzam** [comment]
Yes, (most) property transfer tax account names are in a format eg. "HENSON-PTT".
**Except** one client which is of the format "HENSON-PROPERTY TRANSFER TAX".

I saw it because that one client worked / had amounts for this tax type.

Yes, "Get PTT totals" task does show up.

Also for this tax type "Taxpayer Search" and "Taxpayer profile" seem to match.

**Comment by siphomateke** [comment]
To clarify, the "Get PTT totals" task shows up on client's whose tax account names are in the format "HENSON-PTT"? It shouldn't.

**Comment by rahensonzam** [comment]
No, sorry I messed up and checked the wrong one.
```
Get undefined totals
    Determine ID of account: "henson-ptt"
```
