### ISSUE TITLE
tax types with multiple accounts don't collect totals

### ISSUE THREAD

**Issue by rahensonzam** [nextgensparx/zra-helper#109]
v1.4.0-beta.1-chrome

For different clients with "WITHHOLDING TAX" and "WITHHOLDING TAX-02", the "get pending liabilities" action is only collecting the totals from "WITHHOLDING TAX-02" and not from "WITHHOLDING TAX".

However v1.3.1 works and collects from both.

**Comment by siphomateke** [comment]
Duplicate of #99
