### ISSUE TITLE
Sensitive data in the task export is always hidden, regardless of the setting

### ISSUE THREAD

**Issue by rahensonzam** [nextgensparx/zra-helper#114]
v1.4.0-beta.2

Client names are replaced in the task export (eg. client1) regardless of the setting.

Off: Only client names are changed

On: Output in a wildly different format (machine readable, I guess) with a lot of asterisks.

**Comment by siphomateke** [comment]
The output being in a wildly different format with lots of asterisks is a separate issue. I've opened one for you: #115
