### ISSUE TITLE
Tasks export sometimes full of asterisks when anonymize clients is enabled

### ISSUE THREAD

**Issue by siphomateke** [nextgensparx/zra-helper#115]
**Version**
v1.4.0-beta.2

**Describe the bug**
When the "anonymize clients in export" setting is enabled, the tasks export has 8 asterisks in between every single character. The export looks something like this:

```
********c********l********i********e********n********t********_********1********_********u********s********e********r********n********a********m********e********✔********c********l********i********e********n********t********_********1********_********u********s********e********r********n********a********m********e******** ********c********l********i********e********n********t********_********1********_********u********s********e********r********n********a********m********e******** 
```

**To Reproduce**

1. Enable the "anonymize clients in export" setting
2. Create a client list CSV with one valid client and one client whose password is missing
3. Run any action on that client list
4. The tasks export will now contain 8 asterisks in between every single character

**Expected behavior**
The tasks export shouldn't be filled with asterisks.

**Comment by rahensonzam** [comment]
Was not happening then happened once.

It places exactly 8 asterisks between every single character of the output.
It applies to `text` `csv` and `json`
Only applies when `Hide` is on.

**To Reproduce**
Still don't know yet

**Comment by siphomateke** [comment]
@rahensonzam Thank you, that's very helpful. The issue is that it's trying to hide the passwords of clients whose passwords are blank.
