### ISSUE TITLE
Sometimes some receipts download without pictures, no error message

### ISSUE THREAD

**Issue by rahensonzam** [nextgensparx/zra-helper#129]
**Version**
v1.7.1

**Describe the bug**
Sometimes some receipts and returns download without the pictures for ZRA logo and barcode when using `.mhtml`. It did not show an error in the extension for those.
If you download again it works fine.

Mostly seems to affect Ack-Returns.

Maybe the page is downloading before it's "done", before the pictures load. Just a guess.

**To Reproduce**
Unclear

**Expected behavior**
Receipts should download with pictures or at least give an error in the extension.

**Comment by siphomateke** [comment]
@rahensonzam Could you try reproducing this in 1.6.2 and 1.6.1?
