### ISSUE TITLE
Run duplicate clients (TPIN) in CSV file once, output twice

### ISSUE THREAD

**Issue by rahensonzam** [nextgensparx/zra-helper#130]
**Is your feature request related to a problem? Please describe.**
I have client lists according to person in charge of them. If the tax types for one client are split between two people that client (TPIN, password) appears twice in the list.
If you run "Get pending liabilities" and the password has changed it uses up two tries.
If I remove the second password then I have to copy the output afterwards.
It is better to have the whole output come out "ready to go".

**Describe the solution you'd like**
The extension should detect the multiple same TPIN entries in the `csv`, run that client only once, then output it in the multiple places.

I think the extension should handle this case regardless of whether there are any instances at the time.

**Additional context**
#53

**Comment by siphomateke** [comment]
Additionally, if a client appears multiple times in the list but with different passwords, the extension should not run on that client and the user should be prompted to correct the client.
