### ISSUE TITLE
Set HTML title to filename sometimes not working

### ISSUE THREAD

**Issue by rahensonzam** [nextgensparx/zra-helper#149]
**Version**
v1.9.0, v1.10.0, v1.10.1, v1.11.0 (since added)

**Describe the bug**
Sometimes some receipt's page titles are not set to their filenames. Some are set and some not even in the same run or for the same client.

Applies to all three download actions.

**To Reproduce**
1. Download a bunch of receipts.
2. Observe that some are set, some not.

**Expected behavior**
It should work for all the receipts.

**Additional context**
#132

**Comment by siphomateke** [comment]
Please inspect the downloaded HTML files' head tags to see if there is a difference between those that had their page titles correctly set to their filenames and those that didn't.

**Comment by rahensonzam** [comment]
v1.11.1

Still happening, works 95% of the time.

Could it be to do with when something doesn't load fully?

**Comment by siphomateke** [comment]
I can now reproduce this but only for receipts that are downloaded twice, specifically, payment receipts.

**To Reproduce**
- Find a payment receipt that has at least two payments
- Select the "Get payment receipts" action and adjust its input to match the previously found receipt
- Run the action
- Observe that two files are downloaded for that single receipt and both HTML files' titles won't match their filenames
