### ISSUE TITLE
Add provisional to Accounts approval status feature

### ISSUE THREAD

**Issue by rahensonzam** [nextgensparx/zra-helper#153]
**Is your feature request related to a problem? Please describe.**
Add to feature. Need to know whether returns are provisional or annual/end of year.

**Describe the solution you'd like**
This information is found by reading the ack-returns.
"IT-Provisional" -> Provisional
"IT-Individual", "IT-Non Individual" -> Annual
Include a column in output for Provisional or Annual.

**Describe alternatives you've considered**
Just include column headed "Return Applied Date", not the info wanted but would differentiate them.  This would keep it data only gathered from table. 

**Additional context**
#143 
#152 
https://user-images.githubusercontent.com/32675705/60758450-0e880d00-a017-11e9-9084-b982f936ac4d.png

**Comment by rahensonzam** [comment]
v1.12.0

All rows say "annual" regardless of value.

**Comment by rahensonzam** [comment]
Can you adjust this to make it so that when "check if provisional" is off it shows "Return applied date" in that column.

Differentiating returns is really necessary.

**Comment by siphomateke** [comment]
@rahensonzam I have created a separate issue to track your feature request: #158
