### ISSUE TITLE
Pending liabilities - downloaded last page missing CSS

### ISSUE THREAD

**Issue by rahensonzam** [nextgensparx/zra-helper#163]
**Version**
v1.15.0-rc.0

**Describe the bug**
On the "Get pending liabilities" action with "download pages" the downloaded last page of multi-page pending liability reports is missing it's CSS (every run). It's HTML is all there and correct.

Single page clients are fine.

**To Reproduce**
1. Run "Get pending liabilities" action with "download pages" on multi-page client.
2. Observe the output.

**Expected behavior**
The last page should have CSS with the HTML, the same as the other pages and single page clients.

**Comment by siphomateke** [comment]
@rahensonzam Does the generated HTML for the last page contain any style or links to style elements? Also, does the MHTML version of the last page have the missing CSS? If it does, please check what method it uses for loading CSS - `<style>` or `<link>` tags - and what the tags link to.

**Comment by rahensonzam** [comment]
The generated HTML for the last page contains no styles or style links at all.

However a major point I didn't notice is the last page is **only the table** and not the whole page.

The MHTML version does not download any pages after the first one and gives the error "ImagesInTabFailedToLoad".
