### ISSUE TITLE
Error when logging out: 'Element "logout button" not found'

### ISSUE THREAD

**Issue by nextgensparx** [nextgensparx/zra-helper#22]
Occasionally when logging out, the following error occurs:

```
Element "logout button" not found.
```

This once happened after all the other tasks reported that the ZRA website had an error as can be seen in the following screenshot:

![screenshot of error](https://user-images.githubusercontent.com/19307714/45179109-d60d7c00-b217-11e8-854d-b1cb8e29e25e.png)

It could be that the logout script just doesn't check for ZRA errors.

**Comment by rahensonzam** [comment]
version 0.4.3-dev debug=true

![element logout not found error](https://user-images.githubusercontent.com/32675705/47292197-8d165900-d606-11e8-9549-e7f4d9014122.png)

**Comment by rahensonzam** [comment]
version 0.4.3-dev:debug

![element logout not found error 2](https://user-images.githubusercontent.com/32675705/47478681-9253ed80-d82a-11e8-8e77-0478966e3d90.png)

three times it happened like this.

**Comment by nextgensparx** [comment]
@rahensonzam I've made some changes to try and fix this. Could you try the latest git version (you will have to build it yourself) and see if the issue still persists? It should now throw a ZRA error instead of the logout button not found error if my guess is correct.

**Comment by nextgensparx** [comment]
I've released a new version (v0.4.4) so you don't have to build it yourself.

**Comment by nextgensparx** [comment]
Assumed fixed

**Comment by siphomateke** [comment]
@rahensonzam I've added extra debug options in [v1.1.0](https://github.com/siphomateke/zra-helper/releases/tag/v1.1.0) to help debug this if it occurs again. 

Make sure you enable 'Detailed error information' and 'Collect extra information about missing element errors' so the errors are printed to the log. If you then experience the error again, please provide the outputted log.
