### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by rahensonzam** [nextgensparx/zra-helper#24]
v0.4.3 dev:debug

This happened when downloading return history.
It was when it got to the "`Downloading receipts`" step.

Stack trace

- js/dashboard.js:40222 (log)
- js/dashboard.js:40273 (showError)
- js/dashboard.js:38354 (run)

js/dashboard.js:40222 (log)
```javascript
switch (type) {
  case 'error':
	classes.push('error');
	icon = 'exclamation-circle';
	console.error(text); //40222
	break;
  case 'warning':
	classes.push('warning');
	icon = 'exclamation-triangle';
	console.warn(text);
	break;
  case 'info':
	classes.push('info');
	icon = 'info-circle';
	console.info(text);
	break;
  default:
	console.log(text);
	break;
}
```

**Comment by nextgensparx** [comment]
Did you take a screenshot? I can't tell what the issue is from the information you provided. That stack trace is just for the error message, not the actual error.
